language: objective-c
osx_image: xcode7.2
matrix:
  include:
    - env: IOS_VERSION=9.2
    - env: IOS_VERSION=8.4
before_install:
  - carthage bootstrap --platform iOS --no-use-binaries --verbose
script:
  - set -o pipefail && xcodebuild test -project AppBoard.xcodeproj -scheme AppBoard -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=$IOS_VERSION" ONLY_ACTIVE_ARCH=NO | xcpretty
