language: objective-c
osx_image: xcode7.2
before_install:
  - carthage bootstrap --platform iOS --no-use-binaries --verbose
script:
  - set -o pipefail && xcodebuild test -project AppBoard.xcodeproj -scheme AppBoard -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.2" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
